---
all:
  children:
    el:
        hosts:
          ubuntu:
            ansible_host: localhost
            ansible_port: 2223
            ansible_connection: ssh
            ansible_user: root
            ansible_password: ubuntu123 
            ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    deb:
        hosts:
          alphine:
            ansible_host: localhost
            ansible_port: 2222
            ansible_connection: ssh
            ansible_user: root
            ansible_password: alpine123
            ansible_ssh_common_args: '-o StrictHostKeyChecking=no'   
          fedora:
            ansible_host: localhost
            ansible_port: 2224
            ansible_connection: ssh
            ansible_user: root
            ansible_password: fedora123
            ansible_ssh_common_args: '-o StrictHostKeyChecking=no'  
    local:
        hosts:
          localhost:
            ansible_connection: local